#!/bin/bash

JAVA_BIN="$JAVA_HOME/bin/java"

export DESKTOP_SESSION=gnome
export XDG_SESSION_DESKTOP=gnome
export XDG_CURRENT_DESKTOP=GNOME

JAVA_OPTS="-Dsun.java2d.xrender=true -Dprism.useFontConfig=false -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djava.io.tmpdir=$SNAP_USER_COMMON"

if ! snapctl is-connected dot-java-user-prefs; then
    JAVA_OPTS="$JAVA_OPTS -Djava.util.prefs.userRoot=$SNAP_USER_COMMON/"
fi

if ! snapctl is-connected dot-openrocket-db; then
    JAVA_OPTS="$JAVA_OPTS -Duser.home=$SNAP_USER_COMMON/"
fi

export _JAVA_OPTIONS=$JAVA_OPTS
# Fix font / theme
export JAVA_FONTS=$SNAP/usr/share/fonts/truetype
exec $JAVA_BIN -jar $SNAP/OpenRocket.jar "$@"

