<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>apocalypse</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>29</LastSerialNumber>
            <Stage3Mass>4000.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1058.29</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>1</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>283.495</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>228.6</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>361.54749538948397</CalcMass>
                    <CalcCG>228.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>425.45</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.18</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>100.0</BaseDia>
                    <ShoulderLen>76.2</ShoulderLen>
                    <ShoulderOD>98.43</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>213.78929571200192</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube sup</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>213.78929571200192</CalcMass>
                    <CalcCG>315.9</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>631.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>100.0</OD>
                    <ID>98.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>98.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>73.7088</KnownMass>
                            <Density>958.705</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>355.6</Xb>
                            <CalcMass>47.84680640645568</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>98.06</OD>
                            <ID>95.9104</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>87.883</KnownMass>
                            <Density>2.7098958420476207E-6</Density>
                            <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
                            <Name>Main Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>96.8</Xb>
                            <CalcMass>5.613923693399999</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>685.8</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>37.831027636280204</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Elec Bay</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>37.831027636280204</CalcMass>
                    <CalcCG>55.9</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>111.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>100.0</OD>
                    <ID>98.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>98.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>73.7088</KnownMass>
                            <Density>958.705</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>355.6</Xb>
                            <CalcMass>47.84680640645568</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>98.06</OD>
                            <ID>95.9104</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>68.28534326477062</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube inf1</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>68.28534326477062</CalcMass>
                    <CalcCG>100.9</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>201.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>100.0</OD>
                    <ID>98.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>98.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>73.7088</KnownMass>
                            <Density>958.705</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>355.6</Xb>
                            <CalcMass>47.84680640645568</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>98.06</OD>
                            <ID>95.9104</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>87.883</KnownMass>
                            <Density>6.663512241985067E-5</Density>
                            <Material>1.9 oz. Ripstop Nylon (SkyAngle)</Material>
                            <Name>drogue Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>120.3</Xb>
                            <CalcMass>5.613923693399999</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <Dia>184.4</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>685.8</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>190.71169209130176</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube inf2</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>190.71169209130176</CalcMass>
                    <CalcCG>281.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>563.6</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>100.0</OD>
                    <ID>98.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>98.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>22.15154083044647</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>22.15154083044647</CalcMass>
                            <CalcCG>230.3</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>460.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>54.86</OD>
                            <ID>54.36</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>54.36</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>98.30302513638873</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Custom Fin-1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>127.0</Xb>
                            <CalcMass>98.30302513638873</CalcMass>
                            <CalcCG>220.45869619622917</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>12</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>414.7</TabLength>
                            <TabDepth>23.37</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>406.0,0.0|406.0,2.0|398.0,11.3|395.0,13.0|382.0,58.0|354.0,67.0|320.0,22.0|282.0,25.0|258.0,119.0|228.4,128.0|117.158,25.3139|13.6306,15.2533|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.54997772807576</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 1a</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.54997772807576</CalcMass>
                            <CalcCG>198.96585221328334</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-0.0500037</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>13</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.111,19.9156|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 1b</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0525344</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>14</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>90.9849300733435</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Custom Fin-2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>127.0</Xb>
                            <CalcMass>90.9849300733435</CalcMass>
                            <CalcCG>208.74448258434109</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.5707999999999998</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>15</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>317.5</TabLength>
                            <TabDepth>23.37</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>406.0,0.0|406.0,2.0|398.0,11.3|395.0,13.0|382.0,58.0|354.0,67.0|320.0,22.0|282.0,25.0|258.0,119.0|228.4,128.0|117.158,25.3139|13.6306,15.2533|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 2a</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.50334</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>16</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 2b</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.62988</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>17</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>90.9849300733435</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Custom Fin-3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>127.0</Xb>
                            <CalcMass>90.9849300733435</CalcMass>
                            <CalcCG>208.74448258434109</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>3.1415899999999994</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>18</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>317.5</TabLength>
                            <TabDepth>23.37</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>406.0,0.0|406.0,2.0|398.0,11.3|395.0,13.0|382.0,58.0|354.0,67.0|320.0,22.0|282.0,25.0|258.0,119.0|228.4,128.0|117.158,25.3139|13.6306,15.2533|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 3a</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>3.07195</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>19</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 3b</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-3.09342</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>20</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>90.9849300733435</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Custom Fin-4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>127.0</Xb>
                            <CalcMass>90.9849300733435</CalcMass>
                            <CalcCG>208.74448258434109</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-1.5707999999999998</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>21</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>317.5</TabLength>
                            <TabDepth>23.37</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>406.0,0.0|406.0,2.0|398.0,11.3|395.0,13.0|382.0,58.0|354.0,67.0|320.0,22.0|282.0,25.0|258.0,119.0|228.4,128.0|117.158,25.3139|13.6306,15.2533|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 4a</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-1.50954</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>22</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>20.58888761237905</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Contre fins 4b</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>134.9</Xb>
                            <CalcMass>20.58888761237905</CalcMass>
                            <CalcCG>198.83005192727484</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-1.64916</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>23</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>4.78</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>392.101,0.0|391.0,4.0|387.269,9.0|381.787,10.0|272.906,20.0|114.0,20.0|3.8,7.0|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>11.961913235279138</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>107.9</Xb>
                            <CalcMass>11.961913235279138</CalcMass>
                            <CalcCG>1.59</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>3.18</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <OD>98.06</OD>
                            <ID>54.86</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>11.961913235279138</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>559.6</Xb>
                            <CalcMass>11.961913235279138</CalcMass>
                            <CalcCG>1.59</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>3.18</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>25</SerialNo>
                            <OD>98.06</OD>
                            <ID>54.86</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>15.681351031672762</KnownMass>
                            <Density>680.785</Density>
                            <Material>Birch</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>15.681351031672762</CalcMass>
                            <CalcCG>1.525</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>3.05</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>26</SerialNo>
                            <OD>98.06</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <LaunchLug>
                            <KnownMass>0.4685140502167485</KnownMass>
                            <Density>1199.78</Density>
                            <Material>Polycarbonate</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>540.0</Xb>
                            <CalcMass>0.4685140502167485</CalcMass>
                            <CalcCG>5.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-2.35619</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>10.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>27</SerialNo>
                            <OD>13.43</OD>
                            <ID>11.43</ID>
                        </LaunchLug>
                        <LaunchLug>
                            <KnownMass>0.4685140502167485</KnownMass>
                            <Density>1199.78</Density>
                            <Material>Polycarbonate</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>12.5</Xb>
                            <CalcMass>0.4685140502167485</CalcMass>
                            <CalcCG>5.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-2.35619</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>10.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>28</SerialNo>
                            <OD>13.43</OD>
                            <ID>11.43</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>61.64272321712273</KnownMass>
                    <Density>847.056</Density>
                    <Material>Urethane</Material>
                    <Name>Transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>61.64272321712273</CalcMass>
                    <CalcCG>18.041444744426794</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>44.45</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>29</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>5.21</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>6.35</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>99.06</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>100.0</FrontDia>
                    <RearDia>79.5</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>