Tree.hash = #568AF2
Tree.selectionBackground = #3E6CAD

Slider.trackColor = #616365

SplitPaneDivider.hoverColor = lighten(@background, 5%)

# Custom OpenRocket keys
OR.colors.blue = #7AB6FF
OR.colors.purple = #D4A5FF
OR.colors.yellow = #fccf3d
OR.colors.orange = #FFB86C
OR.colors.red = #ffadad
OR.colors.darkRed = #ffadad
OR.colors.green = #2ECC71

OR.ScrollPane.borderColor = #6e7275
OR.colors.background = #2b2d33
OR.colors.border = #a3a3a3cc
OR.colors.text = $Label.foreground
OR.colors.text.dim = #a5abb8
OR.colors.text.disabled = #808080df
OR.colors.textSelection.foreground = #ffffff
OR.colors.textSelection.background = #3e6cad
OR.colors.info = $OR.colors.blue
OR.colors.warning = $OR.colors.orange
OR.colors.error = $OR.colors.red
OR.colors.darkError = $OR.colors.darkRed
OR.colors.row.lighter = #2b313a
OR.colors.row.darker = #22252c
OR.colors.table.flash = #ffff803c
OR.colors.table.selection = #334266
OR.colors.flightData.textActive = #d4e6ff
OR.colors.flightData.textInactive = #aac9ff7f
OR.colors.multiCompEdit = #ffa5c8
OR.defaults.component.body = 150,175,255
OR.defaults.component.tubeFinSet = 150,184,254
OR.defaults.component.finSet = 150,184,255
OR.defaults.component.launchLug = 142,153,238
OR.defaults.component.railButton = 142,153,238
OR.defaults.component.internal = 181,128,151
OR.defaults.component.massObject = 210,210,210
OR.defaults.component.recoveryDevice = 220,90,90
OR.defaults.component.podSet = 190,190,235
OR.defaults.component.parallelStage = 210,180,195
OR.defaults.lineStyle.generic = SOLID
OR.defaults.lineStyle.massObject = DASHED
OR.colors.motor.border = #ffffffc8
OR.colors.motor.fill = #00000046
OR.colors.cg = #5585fd
OR.colors.cp = #ff486a
OR.colors.url = #abb9ff
OR.colors.componentTree.background = #2b2d33
OR.colors.componentTree.foreground = $Label.foreground
OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
OR.colors.fin.gridMajor = #a4a4e0c5
OR.colors.fin.gridMinor = #8686c945
OR.colors.fin.point = #f27979ff
OR.colors.fin.selectedPoint = #e84e4eff
OR.colors.fin.bodyLine = #ffffff
OR.colors.fin.snapHighlight = #f14d4dff

## OpenRocket icons
OR.icons.default = #ffffff
OR.icons.tintColor = $OR.colors.blue
OR.icons.play = $OR.colors.green
OR.icons.help = $OR.colors.blue
OR.icons.warning.low = $OR.colors.info
OR.icons.warning.normal = $OR.colors.warning
OR.icons.warning.high = $OR.colors.error
OR.icons.override = $OR.colors.info
OR.icons.override.subcomponent = $OR.colors.text.dim
OR.icons.locked = #f1c066
OR.icons.delete = $OR.colors.red
OR.icons.plot = $OR.colors.blue
OR.icons.plus = $OR.colors.green
OR.icons.duplicate = $OR.icons.tintColor
OR.icons.pencil = $OR.colors.yellow
OR.icons.zoomIn = $OR.colors.green
OR.icons.zoomOut = $OR.colors.darkRed
OR.icons.zoomFit = $OR.icons.tintColor
OR.icons.import = $OR.colors.darkRed
OR.icons.export = $OR.colors.green
OR.icons.moveUp = $OR.colors.blue
OR.icons.moveDown = $OR.colors.purple
OR.icons.undo = $OR.colors.darkRed
OR.icons.redo = $OR.colors.blue
OR.icons.imageMountain = $OR.icons.default
OR.icons.imageSun = $OR.icons.default
OR.icons.camera = $OR.icons.tintColor
OR.colors.ruler = $OR.colors.yellow
OR.icons.magnet.red = #E86B55
OR.icons.magnet.white = #E1E3E2
