SplitPaneDivider.hoverColor = darken(@background, 5%)

# OpenRocket custom colors
OR.colors.blue = #2D7FF9
OR.colors.purple = #9F5CF5
OR.colors.yellow = #a68002
OR.colors.orange = #d99800
OR.colors.red = #ff0000
OR.colors.darkRed = #c80000
OR.colors.green = #20C968

OR.colors.background = #ffffff
OR.colors.border = #000000
OR.colors.text = #000000
OR.colors.text.dim = #808080
OR.colors.text.disabled = #808080
OR.colors.textSelection.foreground = $Tree.selectionForeground
OR.colors.textSelection.background = $Tree.selectionBackground
OR.colors.info = $OR.colors.blue
OR.colors.warning = $OR.colors.orange
OR.colors.error = $OR.colors.red
OR.colors.darkError = $OR.colors.darkRed
OR.colors.row.lighter = #ffffff
OR.colors.row.darker = #f5f5f5
OR.colors.table.flash = #ffffcc
OR.colors.table.selection = #d9e9ff
OR.colors.flightData.textActive = #00007f
OR.colors.flightData.textInactive = #00007f7f
OR.colors.multiCompEdit = #aa0064
OR.defaults.component.body = 0,0,240
OR.defaults.component.tubeFinSet = 0,0,200
OR.defaults.component.finSet = 0,0,200
OR.defaults.component.launchLug = 0,0,180
OR.defaults.component.railButton = 0,0,180
OR.defaults.component.internal = 170,0,100
OR.defaults.component.massObject = 0,0,0
OR.defaults.component.recoveryDevice = 255,0,0
OR.defaults.component.podSet = 160,160,215
OR.defaults.component.parallelStage = 198,163,184
OR.defaults.lineStyle.generic = SOLID
OR.defaults.lineStyle.massObject = DASHED
OR.colors.motor.border = #000000c8
OR.colors.motor.fill = #00000064
OR.colors.cg = #0000ff
OR.colors.cp = #ff0000
OR.colors.url = #0000ff
OR.colors.componentTree.background = $Tree.textBackground
OR.colors.componentTree.foreground = $Tree.textForeground
OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.light
OR.colors.fin.gridMajor = #0000ff50
OR.colors.fin.gridMinor = #0000ff1e
OR.colors.fin.point = #c80000ff
OR.colors.fin.selectedPoint = #c80000ff
OR.colors.fin.bodyLine = #000000
OR.colors.fin.snapHighlight = #ff0000

## OpenRocket icons
OR.icons.default = $OR.colors.text
OR.icons.tintColor = $OR.colors.blue
OR.icons.play = $OR.colors.green
OR.icons.help = $OR.colors.blue
OR.icons.warning.low = $OR.colors.info
OR.icons.warning.normal = $OR.colors.warning
OR.icons.warning.high = $OR.colors.error
OR.icons.override = $OR.colors.info
OR.icons.override.subcomponent = $OR.colors.text.dim
OR.icons.locked = #f1c066
OR.icons.delete = $OR.colors.darkRed
OR.icons.plot = #006CB6
OR.icons.plus = $OR.colors.green
OR.icons.duplicate = $OR.icons.tintColor
OR.icons.pencil = $OR.colors.yellow
OR.icons.zoomIn = $OR.colors.green
OR.icons.zoomOut = $OR.colors.darkRed
OR.icons.zoomFit = $OR.icons.tintColor
OR.icons.import = $OR.colors.darkRed
OR.icons.export = $OR.colors.green
OR.icons.moveUp = $OR.colors.blue
OR.icons.moveDown = $OR.colors.purple
OR.icons.undo = $OR.colors.darkRed
OR.icons.redo = $OR.colors.blue
OR.icons.imageMountain = $OR.icons.default
OR.icons.imageSun = $OR.icons.default
OR.icons.camera = $OR.icons.tintColor
OR.colors.ruler = #735a09
OR.icons.magnet.red = #fc5e42
OR.icons.magnet.white = #ffffff
