Tree.hash = #568AF2
Tree.selectionBackground = #3E6CAD

Slider.trackColor = #a3a3a3cc

SplitPaneDivider.hoverColor = lighten(@background, 5%)

# Custom OpenRocket keys
OR.colors.blue = #6EA8FE
OR.colors.purple = #C592FF
OR.colors.yellow = #ffd64a
OR.colors.orange = #FFB066
OR.colors.red = #f68f8f
OR.colors.darkRed = #e56767
OR.colors.green = #66DE93

OR.ScrollPane.borderColor = #8a8a8acc
OR.colors.background = #494c4f
OR.colors.border = #616365
OR.colors.text = #adadad
OR.colors.text.dim = #b6b6b6
OR.colors.text.disabled = #a1a1a1
OR.colors.textSelection.foreground = #ffffff
OR.colors.textSelection.background = #4b6eaf
OR.colors.info = $OR.colors.blue
OR.colors.warning = $OR.colors.orange
OR.colors.error = $OR.colors.red
OR.colors.darkError = $OR.colors.darkRed
OR.colors.row.lighter = #414547
OR.colors.row.darker = #3c3f41
OR.colors.table.flash = #ffff6645
OR.colors.table.selection = #495785
OR.colors.flightData.textActive = #91b7e7
OR.colors.flightData.textInactive = #80a6e67f
OR.colors.multiCompEdit = #de92b0
OR.defaults.component.body = 150,162,255
OR.defaults.component.tubeFinSet = 150,178,255
OR.defaults.component.finSet = 150,178,255
OR.defaults.component.launchLug = 142,153,238
OR.defaults.component.railButton = 142,153,238
OR.defaults.component.internal = 181,128,151
OR.defaults.component.massObject = 210,210,210
OR.defaults.component.recoveryDevice = 220,90,90
OR.defaults.component.podSet = 190,190,235
OR.defaults.component.parallelStage = 210,180,195
OR.defaults.lineStyle.generic = SOLID
OR.defaults.lineStyle.massObject = DASHED
OR.colors.motor.border = #00000064
OR.colors.motor.fill = #00000032
OR.colors.cg = #5585fd
OR.colors.cp = #ff486a
OR.colors.url = #96a7ff
OR.colors.componentTree.background = #494c4f
OR.colors.componentTree.foreground = #adadad
OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
OR.colors.fin.gridMajor = #8787c7c5
OR.colors.fin.gridMinor = #7979bd45
OR.colors.fin.point = #d96c6cff
OR.colors.fin.selectedPoint = #e84e4eff
OR.colors.fin.bodyLine = #ffffff
OR.colors.fin.snapHighlight = #ff3a3aff

## OpenRocket icons
OR.icons.default = #ffffff
OR.icons.tintColor = $OR.colors.blue
OR.icons.play = $OR.colors.green
OR.icons.help = $OR.colors.blue
OR.icons.warning.low = $OR.colors.info
OR.icons.warning.normal = $OR.colors.warning
OR.icons.warning.high = $OR.colors.error
OR.icons.override = $OR.colors.info
OR.icons.override.subcomponent = $OR.colors.text.dim
OR.icons.locked = #f1c066
OR.icons.delete = $OR.colors.red
OR.icons.plot = $OR.colors.blue
OR.icons.plus = $OR.colors.green
OR.icons.duplicate = $OR.icons.tintColor
OR.icons.pencil = $OR.colors.yellow
OR.icons.zoomIn = $OR.colors.green
OR.icons.zoomOut = $OR.colors.darkRed
OR.icons.zoomFit = $OR.icons.tintColor
OR.icons.import = $OR.colors.darkRed
OR.icons.export = $OR.colors.green
OR.icons.moveUp = $OR.colors.blue
OR.icons.moveDown = $OR.colors.purple
OR.icons.undo = $OR.colors.darkRed
OR.icons.redo = $OR.colors.blue
OR.icons.imageMountain = $OR.icons.default
OR.icons.imageSun = $OR.icons.default
