<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>SubAssembly Element Test</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>18</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>426.6301716552979</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>6.107306539734526</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>6.107306539734526</CalcMass>
                    <CalcCG>53.68748632541546</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>76.2</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>3</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.00076</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>24.8006</BaseDia>
                    <ShoulderLen>19.1008</ShoulderLen>
                    <ShoulderOD>23.5991</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>15.040422946044567</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Forward Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>15.040422946044567</CalcMass>
                    <CalcCG>228.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>457.2</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>24.892</OD>
                    <ID>24.13</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>24.13</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>0.0</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>120.65</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>31.75</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>63.5</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>27.8892</OD>
                            <ID>27.8892</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Streamer>
                            <KnownMass>10.038912051168</KnownMass>
                            <Density>0.00664972</Density>
                            <Material>Mylar</Material>
                            <Name>Streamer</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>44.45</Xb>
                            <CalcMass>10.038912051168</CalcMass>
                            <CalcCG>57.15</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>114.3</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Width>114.3</Width>
                            <DragCoefficient>0.138</DragCoefficient>
                        </Streamer>
                        <MassObject>
                            <KnownMass>1.2996672000000002</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>187.325</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>187.325</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>12.192000000000002</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>2.549</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass object - 2.549 g</Name>
                            <KnownCG>282.575</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>282.575</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>1.1277286611933457</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>384.175</Xb>
                            <CalcMass>1.1277286611933457</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>28.702</OD>
                            <ID>24.9428</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.1277286611933457</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>358.775</Xb>
                            <CalcMass>1.1277286611933457</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>28.702</OD>
                            <ID>24.9428</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.1277286611933457</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>288.925</Xb>
                            <CalcMass>1.1277286611933457</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>28.702</OD>
                            <ID>24.9428</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>13.498613632777841</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Aft Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>13.498613632777841</CalcMass>
                    <CalcCG>165.1</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>330.2</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>29.8704</OD>
                    <ID>29.083</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>29.083</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>1.25084668869137</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Engine block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>252.73000000000002</Xb>
                            <CalcMass>1.25084668869137</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>29.083</OD>
                            <ID>24.9428</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <FinSet>
                            <KnownMass>0.9977479979838839</KnownMass>
                            <Density>128.148</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set-1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>257.175</Xb>
                            <CalcMass>0.9977479979838839</CalcMass>
                            <CalcCG>54.72939060773481</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>66.675</RootChord>
                            <TipChord>29.8704</TipChord>
                            <SemiSpan>50.8</SemiSpan>
                            <SweepDistance>67.4141</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <FinSet>
                            <KnownMass>2.8874580315239995</KnownMass>
                            <Density>128.148</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>146.05</Xb>
                            <CalcMass>2.8874580315239995</CalcMass>
                            <CalcCG>61.383333333333326</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.785398</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>101.6</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>34.925</SemiSpan>
                            <SweepDistance>82.55</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <FinSet>
                            <KnownMass>0.9977479979838839</KnownMass>
                            <Density>128.148</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set-2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>257.175</Xb>
                            <CalcMass>0.9977479979838839</CalcMass>
                            <CalcCG>54.72939060773481</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.5708</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>66.675</RootChord>
                            <TipChord>29.8704</TipChord>
                            <SemiSpan>50.8</SemiSpan>
                            <SweepDistance>67.4141</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <FinSet>
                            <KnownMass>0.9977479979838839</KnownMass>
                            <Density>128.148</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set-3</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>257.175</Xb>
                            <CalcMass>0.9977479979838839</CalcMass>
                            <CalcCG>54.72939060773481</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>3.14159</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>66.675</RootChord>
                            <TipChord>29.8704</TipChord>
                            <SemiSpan>50.8</SemiSpan>
                            <SweepDistance>67.4141</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <FinSet>
                            <KnownMass>0.9977479979838839</KnownMass>
                            <Density>128.148</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set-4</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>257.175</Xb>
                            <CalcMass>0.9977479979838839</CalcMass>
                            <CalcCG>54.72939060773481</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>-1.5708</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <FinCount>1</FinCount>
                            <RootChord>66.675</RootChord>
                            <TipChord>29.8704</TipChord>
                            <SemiSpan>50.8</SemiSpan>
                            <SweepDistance>67.4141</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Ring>
                            <KnownMass>1.1277286611933457</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>323.85</Xb>
                            <CalcMass>1.1277286611933457</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>28.702</OD>
                            <ID>24.9428</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.1277286611933457</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>282.575</Xb>
                            <CalcMass>1.1277286611933457</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>28.702</OD>
                            <ID>24.9428</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>